<?php

/**
 * @file
 * Code for the Form Colorpicker module.
 */

/**
 * Implements hook_elements().
 */
function fapi_colorpicker_element_info() {
  // This is the definition for the new form API element.
  return [
    'colorpicker' => [
      '#input' => TRUE,
      '#element_validate' => ['fapi_colorpicker_validate'],
      '#fapi_colorpicker_background' => 'select.png',
      '#process' => ['ajax_process_form'],
      '#theme' => 'colorpicker',
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function fapi_colorpicker_theme() {
  return [
    'colorpicker' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Callback theme for the new form element.
 */
function theme_colorpicker($variables) {
  $element = $variables['element'];

  if (!isset($element['#id'])) {
    $element['#id'] = drupal_html_id('edit-' . implode('-', $element['#parents']));
  }

  $class = ['form-colorpicker'];
  $output = '';
  unset($element['#prefix']);
  unset($element['#suffix']);

  $path = libraries_get_path('colorpicker');

  // Decide what background to use to render the element. In order to ensure the background exists, we create an array of
  // the two possibilities, that we will use to compare the value submitted in the Form API definition.
  $backgrounds = ['select.png', 'select2.png'];
  // Now we check to see if the value in the Form API definition is valid. If it is, we use it, if it's not, we use a default value.
  $background = (in_array($element['#fapi_colorpicker_background'], $backgrounds)) ? $element['#fapi_colorpicker_background'] : 'select.png';
  // Since we know the background, we can then get the URL of it to pass to the javascript function.
  $background_url = base_path() . $path . '/images/' . $background;
  // Next we determine what the default value for the form element is. This will also be passed to the javascript function.
  if (isset($element['#value']) && strlen($element['#value'])) {
    $default_color = '#' . $element['#value'];
  }
  elseif (isset($element['#default_value']) && strlen($element['#default_value']) == 6 && preg_match('/^[0-9a-f]{6}$/i', $element['#default_value'])) {
    $default_color = '#' . strtolower($element['#default_value']);
  }
  else {
    $default_color = "#ffffff";
  }
  // Build an array of all the settings to be used by the javascript function.
  $settings = [
    'ids' => [$element['#id']],
    'backgrounds' => [$background_url],
    'backgroundColors' => [$default_color],
    $element['#id'] . '-defaultColor' => $default_color,
  ];

  // Attach the 3rd party CSS and JS files, and attach the module's JS files.
  $element['#attached'] = [
    'css' => [
      // Add the 3rd party CSS files required for the form elmeent.
      $path . '/css/colorpicker.css',
    ],
    'js' => [
      // Add the 3rd party JS files required for the form element.
      $path . '/js/colorpicker.js',
      // Add the module js files.
      drupal_get_path('module', 'fapi_colorpicker') . '/js/fapi_colorpicker.js',
    ],
  ];
  // If IE6 support is enabled, attach the inline CSS and JS that will reside in conditional comments.
  if (variable_get('fapi_colorpicker_ie6_support', 0)) {
    $ie6_path = base_path() . drupal_get_path('module', 'fapi_colorpicker') . '/twin_helix/';
    $path_to_pngfix = $ie6_path . 'iepngfix.htc';
    $path_to_tilebg = $ie6_path . 'iepngfix_tilebg.js';
    $css = '<!--[if lt IE 7]>' .
      '.inner_wrapper, .color_picker, .colorpicker_color div, .colorpicker_color div div  { behavior: url("' . $path_to_pngfix . '") } ' .
      '<![endif]-->';
    $element['#attached']['css'][] = [
      'data' => $css,
      'type' => 'inline',
    ];
    $js = 'var script = document.createElement("script"); script.type = "text/javascript";';
    $js .= 'script.src = "' . $path_to_tilebg . '";';
    $js .= 'document.getElementsByTagName("head")[0].appendChild(script);';
    $element['#attached']['js'][] = [
      'data' => $js,
      'type' => 'inline',
    ];
  }

  // And we pass the settings in a namespace to the Javascript.
  $element['#attached']['js'][] = [
    'data' => ['jqueryColorpicker' => $settings],
    'type' => 'setting',
  ];
  // Over the next few lines we build the output of the element in HTML and to send to the browser.
  _form_set_class($element, $class);

  $output .= '<div class="fapi_colorpicker">';
  $output .= '<div id="' . $element['#id'] . '-inner_wrapper" class="inner_wrapper">';
  $output .= '<div class="color_picker" style="background-color:' . $default_color . '">';
  $output .= '<span class="hash">#</span>';
  $name = $element['#name'] ?? $element['#id'];
  $value = isset($element['#value']) ? check_plain($element['#value']) : '';
  $output .= '<input type="text"' . ' maxlength="6"' . ' name="' . $name . '" id="' . $element['#id'] . '"' . ' size="7"' . ' value="' . $value . '"' . drupal_attributes($element['#attributes']) . ' />';
  $output .= '<div class="description">' . t('Enter a hexidecimal color value. Enabling javascript will replace this input with a graphical color selector.') . '</div>';
  $output .= '</div>';
  $output .= '</div>';
  if (isset($element['#cardinality'])) {
    if ($element['#cardinality'] == FIELD_CARDINALITY_UNLIMITED) {
      $output .= '<div>' . l(t('Remove'), '#', ['html' => TRUE, 'attributes' => ['onclick' => 'jQuery(\'#' . $element['#id'] . '\').val(\'\'); jQuery(\'#' . $element['#id'] . '\').parents(\'tr\').hide(); return false;']]) . '</div>';
    }
    else {
      $output .= '<div>' . l(t('Clear'), '#', ['html' => TRUE, 'attributes' => ['onclick' => 'jQuery(\'#' . $element['#id'] . '\').val(\'\'); jQuery(\'#' . $element['#id'] . '\').parents(\'.color_picker\').css("backgroundColor", "#FFF"); return false']]) . '</div>';
    }
  }
  $output .= '</div>';

  $element['#children'] = $output;
  $element['#theme'] = 'form_element';
  return drupal_render($element);
}

/**
 * Validation function for the new form element.
 */
function fapi_colorpicker_validate($element, &$form_state) {
  // All values must be 6 characters in length (will probably add support for 3 character definitions and predifined colors in version 2.
  if ($element['#value'] != '' && strlen($element['#value']) != 6) {
    form_error($element, t('Color values must be exactly six characters in length'));
  }
  // All values must not include the hash symbol.
  elseif ($element['#value'] != '' && preg_match('/^#/', $element['#value'])) {
    form_error($element, t('Do not include the hash symbol (#) when entering colors'));
  }
  // All values must be hexadecimal values.
  elseif ($element['#value'] != '' && !preg_match('/^[0-9a-f]{6}$/i', $element['#value'])) {
    form_error($element, t("You entered an invalid value for the color. Colors must be hexadecimal, and can only contain the characters '0' to '9' and 'a' to 'f'."));
  }
}
